# Generated by Django 6.0.3 on 2026-03-27 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetask',
            options={'ordering': ['-assigned_date']},
        ),
        migrations.AddField(
            model_name='employeetask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='deadline',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('carry_forward', 'Carry Forward'), ('not_done', 'Not Done'), ('department_delay', 'Department Delay')], db_index=True, default='pending', max_length=30),
        ),
    ]
