# Generated by Django 6.0.3 on 2026-03-28 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_employeetask_options_employeetask_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetask',
            options={},
        ),
        migrations.AddField(
            model_name='employeetask',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('done', 'Done (Waiting Approval)'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
    ]
