# Generated by Django 6.0.3 on 2026-04-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('done', 'Done (Waiting Approval)'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
    ]
