# Generated by Django 6.0.3 on 2026-04-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='is_resubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('done', 'Done (Waiting Approval)'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='assigned', max_length=20),
        ),
    ]
