# Generated by Django 6.0.3 on 2026-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskassignment_is_resubmitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktimelog',
            name='is_rework',
            field=models.BooleanField(default=False),
        ),
    ]
