# Generated by Django 6.0.3 on 2026-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasktimelog_is_rework'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='completion_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
